version: '3.8'

services:
  # Database PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: scraperdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scraper-net

  # Backend Node.js (Thay đổi ở đây)
  backend:
    build: ./backend-node  # <-- Trỏ vào thư mục mới
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/scraperdb
    depends_on:
      - db
    networks:
      - scraper-net
    deploy:
      resources:
        limits:
          cpus: '1.0'     # Vẫn giữ limit 1 CPU
          memory: 1024M   # Vẫn giữ limit 1GB RAM

  # Frontend React
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    networks:
      - scraper-net

volumes:
  postgres_data:

networks:
  scraper-net: